import { defineType, defineField } from 'sanity';
import { seoFields } from './seo';

export const bookMeetPage = defineType({
  name: 'bookMeetPage',
  type: 'document',
  title: 'Book A Meet Page',
  groups: [
    { name: 'general', title: 'General' },
    { name: 'fullTime', title: 'Full-Time' },
    { name: 'partTime', title: 'Part-Time' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'title',
      type: 'string',
      title: 'Page title',
      group: 'general',
      initialValue: 'Book A Meet',
      validation: (r) => r.required(),
      description: 'Used for SEO and the visible page heading.',
    }),
    defineField({
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      group: 'general',
      description: 'Used for reference in the CMS. The live URL is fixed at /book-a-meet.',
      options: { source: 'title', maxLength: 96 },
      initialValue: { current: 'book-a-meet' },
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'subtitle',
      type: 'text',
      title: 'Page subtitle',
      group: 'general',
      rows: 3,
      description: 'Supporting text shown beneath the page title.',
    }),
    defineField({
      name: 'fullTimeTitle',
      type: 'string',
      title: 'Section title',
      group: 'fullTime',
      initialValue: 'Full-Time',
    }),
    defineField({
      name: 'fullTimeBody',
      type: 'text',
      title: 'Section body',
      group: 'fullTime',
      rows: 6,
    }),
    defineField({
      name: 'fullTimeImage',
      type: 'image',
      title: 'Section image',
      group: 'fullTime',
      options: { hotspot: true },
      description: 'Optional. Falls back to institute photography when empty.',
    }),
    defineField({
      name: 'fullTimeCta',
      type: 'ctaButton',
      title: 'Booking button',
      group: 'fullTime',
      description: 'Links to the Full-Time booking form page.',
    }),
    defineField({
      name: 'partTimeTitle',
      type: 'string',
      title: 'Section title',
      group: 'partTime',
      initialValue: 'Part-Time',
    }),
    defineField({
      name: 'partTimeBody',
      type: 'text',
      title: 'Section body',
      group: 'partTime',
      rows: 6,
    }),
    defineField({
      name: 'partTimeImage',
      type: 'image',
      title: 'Section image',
      group: 'partTime',
      options: { hotspot: true },
      description: 'Optional. Falls back to institute photography when empty.',
    }),
    defineField({
      name: 'partTimeCta',
      type: 'ctaButton',
      title: 'Booking button',
      group: 'partTime',
      description: 'Links to the Part-Time booking form page.',
    }),
    ...seoFields,
  ],
});
