import { defineType, defineField } from 'sanity';

export const siteSettings = defineType({
  name: 'siteSettings',
  type: 'document',
  title: 'Site Settings',
  groups: [
    { name: 'organization', title: 'Organization / NAP' },
    { name: 'nav', title: 'Navigation' },
    { name: 'footer', title: 'Footer' },
  ],
  fields: [
    defineField({
      name: 'organizationName',
      type: 'string',
      title: 'Organization name',
      group: 'organization',
      initialValue: 'Milton Quran Institute',
      validation: (r) => r.required(),
      description: 'Official business name used for SEO and entity signals. Must remain "Milton Quran Institute".',
    }),
    defineField({
      name: 'footerAddress',
      type: 'string',
      title: 'Address',
      group: 'organization',
      validation: (r) => r.required(),
      description: 'Verified Milton Quran Institute street address (shown in footer + schema).',
    }),
    defineField({
      name: 'footerPhone',
      type: 'string',
      title: 'Phone',
      group: 'organization',
      validation: (r) => r.required(),
      description: 'Verified Milton Quran Institute phone number.',
    }),
    defineField({
      name: 'footerEmail',
      type: 'string',
      title: 'Primary Email (legacy)',
      group: 'organization',
      validation: (r) => r.email(),
      description: 'Fallback when Footer Emails is empty. Prefer adding entries under Footer Emails.',
    }),
    defineField({
      name: 'footerEmails',
      type: 'array',
      title: 'Footer Emails',
      group: 'footer',
      of: [{ type: 'labeledEmail' }],
      description: 'Contact emails shown in the footer, each with a title (e.g. Part-Time Programs).',
    }),
    defineField({
      name: 'navLinks',
      type: 'array',
      title: 'Navigation Links',
      group: 'nav',
      of: [{ type: 'navLink' }],
      description: 'Text navigation links shown in the header.',
    }),
    defineField({
      name: 'navCtaButtons',
      type: 'array',
      title: 'Navigation CTA Buttons',
      group: 'nav',
      of: [{ type: 'pageCtaButton' }],
      description: 'Prominent header buttons (e.g. Book A Meet, Donate). Link to internal pages only.',
    }),
    defineField({
      name: 'footerTagline',
      type: 'text',
      title: 'Footer Tagline',
      group: 'footer',
      rows: 2,
    }),
    defineField({
      name: 'footerQuickLinks',
      type: 'array',
      title: 'Footer Quick Links',
      group: 'footer',
      of: [{ type: 'navLink' }],
    }),
    defineField({
      name: 'footerProgramLinks',
      type: 'array',
      title: 'Footer Program Links',
      group: 'footer',
      of: [{ type: 'navLink' }],
    }),
    defineField({
      name: 'socialLinks',
      type: 'array',
      title: 'Social Media Links',
      group: 'organization',
      description: 'Profile URLs used in the footer and schema.org sameAs.',
      of: [
        {
          type: 'object',
          fields: [
            defineField({
              name: 'platform',
              type: 'string',
              title: 'Platform',
              validation: (r) => r.required(),
              options: {
                list: [
                  { title: 'Instagram', value: 'instagram' },
                  { title: 'Facebook', value: 'facebook' },
                  { title: 'YouTube', value: 'youtube' },
                  { title: 'Twitter / X', value: 'twitter' },
                  { title: 'LinkedIn', value: 'linkedin' },
                  { title: 'TikTok', value: 'tiktok' },
                ],
              },
            }),
            defineField({ name: 'url', type: 'url', title: 'Profile URL', validation: (r) => r.required() }),
          ],
          preview: { select: { platform: 'platform' }, prepare: ({ platform }: { platform?: string }) => ({ title: platform || 'Social' }) },
        },
      ],
    }),
    defineField({
      name: 'footerCopyright',
      type: 'string',
      title: 'Footer Copyright',
      group: 'footer',
      description: 'e.g. © {year} Milton Quran Institute. All rights reserved.',
    }),
  ],
});
